makeCacheMatrix <- function(mat = matrix()) 
{
  
  ## First, initialize the inverse property
  i <- NULL
  
  ## Then, set the matrix
  set <- function(matrix) 
  {
    mat <<- matrix
    i <<- NULL
  }
  
  ## Get the matrix
  get <- function() 
  {
    ## Return the matrix
    mat
  }
  
  ## After that, set the inverse of the matrix
  setInverse <- function(inverse) 
  {
    i <<- inverse
  }
  
  ## Get the inverse of the matrix
  getInverse <- function() 
  {
    ## Return the inverse property
    i
  }
  
  ## Return the set of methods
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}

############################################################################
## 1. The function returns the inverse of matrix generated by makeCacheMatrix.
## 2. In the inverse is already calculated given the same matrix, then it
## retrieves the inverse from the cache.
############################################################################

cacheSolve <- function(x, ...) 
{
  
  ## Return a matrix that is the inverse of 'x'
  mat <- x$getInverse()
  
  ## If it is alreaday generated, retrieve it.
  if(!is.null(mat)) 
  {
    message("getting cached data")
    return(mat)
  }
  
  ## If not, get the matrix from our object.
  data <- x$get()
  
  ## Then, by using the matrix multiplication, we calculate the inverse.
  mat <- solve(data) %*% data
  
  ## Finally, set the inverse to an object.
  x$setInverse(mat)
  
  ## Return the matrix
  mat
}
